### ISSUE TITLE
Crash when creating a new notification on mac.

### ISSUE THREAD

**Issue by rafaskb** [spookygames/gdx-notifications#3] opened 2019-06-01 19:20 UTC
Calling `handler.showNotification` freezes the game without any errors or stacktraces.

Code being called:
```java
NotificationHandler handler = new DesktopNotificationHandler();
handler.showNotification(new NotificationParameters(1, "Notification for the people", "Lorem ipsum"));
```

Dependency being used (Desktop):
```groovy
compile 'net.spookygames.gdx:gdx-notifications-desktop-os:0.0.2'
```

Details:
macOS 1.14.4
libgdx 1.9.9
lwjgl3

**Comment by rafaskb** [comment] 2019-06-01 19:29
Happens when running Jre6Notifier line 28.

**Comment by SimonIT** [comment] 2019-06-01 20:18
Can't reproduce on windows. I got no mac to test it

**Comment by arthurtemple** [comment] 2019-06-15 12:42
Unable to reproduce on macOS 10.14.5 with the [demo application](https://github.com/SimonIT/gdx-notifications-app), unfortunately. The first notification is a bit slow to show up but that is all.

![image](https://user-images.githubusercontent.com/953645/59551549-a1370e00-8f7b-11e9-9288-8f645980280f.png)

Would you have an example project to share?

You might have better luck discussing the issue with the developer of the [java-to-OS-notify](https://github.com/wokier/java-to-OS-notify) library.

**Comment by rafaskb** [comment] 2019-06-16 10:09
The demo application doesn't compile for me when I run `gradlew desktop:run`.

```
> Task :core:compileJava FAILED
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/Users/rafa/Downloads/gdx-notifications-app-master/core/src/net/spookygames/gdx/notificationsapp/NotificationsApp.java:51: error: incompatible types: String cannot be converted to int
                NotificationParameters parameters = new NotificationParameters(titleTextField.getText(), textTextArea.getText(), notificationID);
                                                                                                     ^
```

**Comment by SimonIT** [comment] 2019-06-16 12:54
@rafaskb My fault, used my local version to built the app. It's fixed in my last commit SimonIT/gdx-notifications-app@1da62ad

**Comment by rafaskb** [comment] 2019-06-16 18:30
The demo application builds now, and notifications work just fine. I tested in my TypingLabel test app and notifications worked there as well, but just like gdx-notifications-app, it uses lwjgl2. The crash seems to be specific to lwjgl3.

I tested this exact same code in both backends, lwjgl3 causes the game to freeze forever.

```groovy
jcenter()
maven { url "http://dl.bintray.com/spookygames/oss" }

compile "net.spookygames.gdx:gdx-notifications:0.0.2"
compile "net.spookygames.gdx:gdx-notifications-desktop-os:0.0.2"
```

```java
final NotificationHandler handler = new DesktopNotificationHandler();
final NotificationParameters notificationParameters = new NotificationParameters(12, "Title", "Text");
handler.showNotification(notificationParameters);
```

**Comment by arthurtemple** [comment] 2019-06-17 14:31
The call to `java.awt.Toolkit.getDefaultToolkit()` seems to make it all go haywire. You may try to add the line in your main() method to see this happen.

I don't really know how _gdx-notifications_ could prevent the issue as it looks like a Lwjgl3 bug to me.

**Comment by rafaskb** [comment] 2019-06-17 14:45
Confirmed, that line alone crashes the entire application in lwjgl3.

**Comment by arthurtemple** [comment] 2019-06-17 16:02
As an additional note, [the first post regarding support for Lwjgl3](https://www.badlogicgames.com/wordpress/?p=3870) mentioned lackluster OSX support:

> On Mac OS X, no support for AWT and Swing. If your desktop app relied on either APIs to show dialogs or read images, you will have to find a replacement. LWJGL 3 has added support for native dialogs, which should cover all bases. I’ll expose these APIs in Lwjgl3Window soon.

I am unsure as to whether these bugs were solved or not.

One way of getting it working on a macOS machine would be to have an AWT-less build of the java-to-OS-notify library.
Furthermore, in case you run your software on machines you own, installing Growl, [terminal-notifier](https://github.com/alloy/terminal-notifier) or Snarl would make them take precedence on the AWT-based notifier.

**Comment by arthurtemple** [comment] 2022-09-04 16:13
Closing now, please re-open if there still is a need to fix.

**Closed as not planned by arthurtemple** 2022-09-04 16:13 UTC
